_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 6
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ortho_all/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ANCHOR_GENERATOR:
    SIZES: [[8], [16], [32], [64], [128]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
DATASETS:
  TRAIN: ('coco_trainval_novel_50shot',)
  TEST: ('test_novel',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (10000, )
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, )
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_50shot"