_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  #train resume weights dir
  # WEIGHTS: "checkpoints/R-50.pkl"
  WEIGHTS: "checkpoints/R-101.pkl"
  #test weights dir
  MASK_ON: False
  #  RETINANET:
  #    SCORE_THRESH_TEST: 0.5
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 6
    #SCORE_THRESH_TEST: 0.5
DATASETS:
  TRAIN: ('jiaonang_train_base',)
  TEST: ('test_base',)
SOLVER:
  IMS_PER_BATCH: 4
  STEPS: (8500, )
  MAX_ITER: 10000
  BASE_LR: 0.001
  # WARMUP_ITERS: 1000
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_jiaonang_base"