_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  #train resume weights dir
  # WEIGHTS: "checkpoints/R-50.pkl"
  # WEIGHTS: "checkpoints/R-101.pkl"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  #test weights dir
  MASK_ON: False
  #  RETINANET:
  #    SCORE_THRESH_TEST: 0.5
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 13
    #SCORE_THRESH_TEST: 0.5
DATASETS:
  TRAIN: ('ortho_train_base',)
  TEST: ('test_base',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (10000, 15000, 20000)
  GAMMA: 0.5
  MAX_ITER: 30000
  BASE_LR: 0.005
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 500
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ortho_base"