_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ortho_all_10shot/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
    OUTPUT_LAYER: "CosineSimOutputLayers"
    # FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  # PROPOSAL_GENERATOR:
    # FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_10shot',)
  TEST: ('ortho_test_all',)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  STEPS: (10000, )
  GAMMA: 0.5
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 10
TEST:
  EVAL_PERIOD: 500
INPUT:
INPUT:
  MIN_SIZE_TRAIN: (640, 768, )
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_10shot"