_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 6
DATASETS:
  TRAIN: ('ortho_train_base',)
  TEST: ('ortho_test_base',)
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (2000, 8000)
  MAX_ITER: 10000
  BASE_LR: 0.01
  WARMUP_ITERS: 1000
OUTPUT_DIR: "outputs/faster_rcnn/faster_rcnn_R_101_FPN_ortho_base"
